//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Medical_System
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public int AID { get; set; }
        public Nullable<System.DateTime> DateIssued { get; set; }
    }
}
