use MedicalSystem

Go

Insert Into DiseaseType (Name)
Values ('Mental'), ('Physical')

Go

Insert Into Disease (Name,Disease_type)
Values
('Acute stress disorder',1),
('Adjustment disorders',1),
('Agoraphobia',1),
('Alcohol and substance abuse',1),
('Alcohol and substance dependence',1),
('Amnesia',1),
('Anxiety disorders',1),
('Anorexia nervosa',1),
('Antisocial personality disorder',1),
('Aspergers syndrome',1),
('Attention deficit hyperactivity disorder',1),
('Akiltism',1),
('Autism',1),
('Avoidant personality disorder',1),
('Bibliomania',1),
('Binge eating disorder',1),
('Bipolar disorder',1),
('Bipolar I disorder',1),
('Bipolar II disorder',1),
('Body dysmorphic disorder',1),
('Borderline personality disorder',1),
('Brief psychotic disorder',1),
('Bruxism',1),
('Bulimia nervosa',1),
('Conduct disorder',1),
('Conversion disorder',1),
('Cyclothymia',1),
('Delusional disorder',1),
('Dependent personality disorder',1),
('Depersonalization disorder',1),
('Depressive personality disorder',1),
('Dermotillomania',1),
('Disorder of written expression',1),
('Dissocial personality disorder',1),
('Dissociative fugue',1),
('Dissociative identity disorder',1),
('Down syndrome',1),
('Dyslexia',1),
('Dyspareunia',1),
('Dysthymia',1),
('Encopresis',1),
('Enuresis (bedwetting)',1),
('Erotomania',1),
('Exhibitionism',1),
('Expressive language disorder',1),
('Female and male orgasmic disorders',1),
('Female sexual arousal disorder',1),
('Folie à deux',1),
('Frotteurism',1),
('Gambling addiction',1),
('Gender identity disorder',1),
('Generalized anxiety disorder',1),
('General adaptation syndrome',1),
('Histrionic personality disorder',1),
('Primary hypersomnia',1),
('Hypoactive sexual desire disorder',1),
('Hypochondriasis',1),
('Hypomania',1),
('Hyperkinetic syndrome',1),
('Hypersexuality',1),
('Hysteria',1),
('Intermittent explosive disorder',1),
('Joubert syndrome',1),
('Kleptomania',1),
('Major depressive disorder',1),
('Male erectile disorder',1),
('Mania',1),
('Mental retardation',1),
('Munchausen syndrome',1),
('Mathematics disorder',1),
('Minor depressive disorder',1),
('Narcissistic personality disorder',1),
('Narcolepsy',1),
('Nightmare disorder',1),
('Obsessive-compulsive disorder',1),
('Obsessive-compulsive personality disorder',1),
('Onychophagia',1),
('Oppositional defiant disorder',1),
('Pain disorder',1),
('Panic attacks',1),
('Panic disorder',1),
('Paranoid personality disorder',1),
('Passive-aggressive personality disorder',1),
('Pathological gambling',1),
('Pervasive developmental disorder',1),
('Pica',1),
('Post-traumatic stress disorder',1),
('Premature ejaculation',1),
('Primary insomnia',1),
('Psychotic disorder',1),
('Pyromania',1),
('Reading disorder',1),
('Retts disorder',1),
('Rumination syndrome',1),
('Sadistic personality disorder',1),
('Schizoaffective disorder',1),
('Schizoid personality disorder',1),
('Schizophrenia',1),
('Schizophreniform disorder',1),
('Schizotypal personality disorder',1),
('Seasonal affective disorder',1),
('Self-defeating personality disorder',1),
('Separation anxiety disorder',1),
('Shared psychotic disorder',1),
('Sleep disorder',1),
('Sleep terror disorder',1),
('Sleepwalking disorder',1),
('Social phobia',1),
('Somatization disorder',1),
('Specific phobias',1),
('Stereotypic movement disorder',1),
('Stuttering',1),
('Tourette syndrome',1),
('Transient tic disorder',1),
('Trichotillomania',1),
('Acinetobacter infections',2),
('Actinomycosis',2),
('African trypanosomiasis',2),
('AIDS',2),
('Amebiasis',2),
('Anaplasmosis',2),
('Anthrax',2),
('Arcanobacterium haemolyticum infection',2),
('Argentine hemorrhagic fever',2),
('Ascariasis',2),
('Aspergillosis',2),
('Astrovirus infection',2),
('Babesiosis',2),
('Bacillus cereus infection',2),
('Bacterial pneumonia',2),
('Bacterial vaginosis',2),
('Bacteroides infection',2),
('Balantidiasis',2),
('Baylisascaris infection',2),
('BK virus infection',2),
('Black piedra',2),
('Blastocystis hominis infection',2),
('Blastomycosis',2),
('Bolivian hemorrhagic fever',2),
('Borrelia infection',2),
('Botulism (and Infant botulism)',2),
('Brazilian hemorrhagic fever',2),
('Brucellosis',2),
('Bubonic plague',2),
('Burkholderia infection',2),
('Buruli ulcer',2),
('Calicivirus infection (Norovirus and Sapovirus)',2),
('Campylobacteriosis',2),
('Candidiasis (Moniliasis; Thrush)',2),
('Cat-scratch disease',2),
('Cellulitis',2),
('Chagas Disease (American trypanosomiasis)',2),
('Chancroid',2),
('Chickenpox',2),
('Chlamydia',2),
('Chlamydophila pneumoniae infection',2),
('Cholera',2),
('Chromoblastomycosis',2),
('Clonorchiasis',2),
('Clostridium difficile infection',2),
('Coccidioidomycosis',2),
('Colorado tick fever (CTF)',2),
('Acute viral rhinopharyngitis: Acute coryza',2),
('Creutzfeldt-Jakob disease (CJD)',2),
('Crimean-Congo hemorrhagic fever',2),
('Cryptococcosis',2),
('Cryptosporidiosis',2),
('Cutaneous larva migrans (CLM)',2),
('Cyclosporiasis',2),
('Cysticercosis',2),
('Cytomegalovirus infection',2),
('Dengue fever',2),
('Dientamoebiasis',2),
('Diphtheria',2),
('Diphyllobothriasis',2),
('Dracunculiasis',2),
('Ebola hemorrhagic fever',2),
('Echinococcosis',2),
('Ehrlichiosis',2),
('Enterobiasis (Pinworm infection)',2),
('Enterococcus infection',2),
('Enterovirus infection',2),
('Epidemic typhus',2),
('Erythema infectiosum (Fifth disease)',2),
('Exanthem subitum (Sixth disease)',2),
('Fasciolopsiasis',2),
('Fasciolosis',2),
('Fatal familial insomnia (FFI)',2),
('Filariasis',2),
('Food poisoning by Clostridium perfringens',2),
('Free-living amebic infection',2),
('Fusobacterium infection',2),
('Clostridial myonecrosis',2),
('Geotrichosis',2),
('Gerstmann-Sträussler-Scheinker syndrome',2),
('Giardiasis',2),
('Glanders',2),
('Gnathostomiasis',2),
('Gonorrhea',2),
('Granuloma inguinale (Donovanosis)',2),
('Group A streptococcal infection',2),
('Group B streptococcal infection',2),
('Haemophilus influenzae infection',2),
('Hand, foot and mouth disease (HFMD)',2),
('Hantavirus Pulmonary Syndrome (HPS)',2),
('Helicobacter pylori infection',2),
('Hemolytic-uremic syndrome (HUS)',2),
('Hemorrhagic fever with renal syndrome',2),
('Hepatitis A',2),
('Hepatitis B',2),
('Hepatitis C',2),
('Hepatitis D',2),
('Hepatitis E',2),
('Herpes simplex',2),
('Histoplasmosis',2),
('Hookworm infection',2),
('Human bocavirus infection',2),
('Human ewingii ehrlichiosis',2),
('Human granulocytic anaplasmosis (HGA)',2),
('Human metapneumovirus infection',2),
('Human monocytic ehrlichiosis',2),
('Human papillomavirus (HPV) infection',2),
('Human parainfluenza virus infection',2),
('Hymenolepiasis',2),
('Epstein-Barr Virus Infectious Mononucleosis',2),
('Influenza (flu)',2),
('Isosporiasis',2),
('Kawasaki disease',2),
('Keratitis',2),
('Kingella kingae infection',2),
('Kuru',2),
('Lassa fever',2),
('Legionellosis (Legionnaires disease)',2),
('Legionellosis (Pontiac fever)',2),
('Leishmaniasis',2),
('Leprosy',2),
('Leptospirosis',2),
('Listeriosis',2),
('Lyme disease (Lyme borreliosis)',2),
('Lymphatic filariasis (Elephantiasis)',2),
('Lymphocytic choriomeningitis',2),
('Malaria',2),
('Marburg hemorrhagic fever (MHF)',2),
('Measles',2),
('Melioidosis (Whitmores disease)',2),
('Meningitis',2),
('Meningococcal disease',2),
('Metagonimiasis',2),
('Microsporidiosis',2),
('Molluscum contagiosum (MC)',2),
('Monkeypox',2),
('Mumps',2),
('Murine typhus (Endemic typhus)',2),
('Mycoplasma pneumonia',2),
('Mycetoma',2),
('Myiasis',2),
('Neonatal conjunctivitis (Ophthalmia neonatorum)',2),
('Variant Creutzfeldt-Jakob disease (vCJD, nvCJD)',2),
('Nocardiosis',2),
('Onchocerciasis',2),
('Paracoccidioidomycosis',2),
('Paragonimiasis',2),
('Pasteurellosis',2),
('Pediculosis capitis (Head lice)',2),
('Pediculosis corporis (Body lice)',2),
('Pediculosis pubis (Pubic lice, Crab lice)',2),
('Pelvic inflammatory disease (PID)',2),
('Pertussis (Whooping cough)',2),
('Plague',2),
('Pneumococcal infection',2),
('Pneumocystis pneumonia (PCP)',2),
('Pneumonia',2),
('Poliomyelitis',2),
('Prevotella infection',2),
('Primary amoebic meningoencephalitis (PAM)',2),
('Progressive multifocal leukoencephalopathy',2),
('Psittacosis',2),
('Q fever',2),
('Rabies',2),
('Rat-bite fever',2),
('Respiratory syncytial virus infection',2),
('Rhinosporidiosis',2),
('Rhinovirus infection',2),
('Rickettsial infection',2),
('Rickettsialpox',2),
('Rift Valley fever (RVF)',2),
('Rocky Mountain spotted fever (RMSF)',2),
('Rotavirus infection',2),
('Rubella',2),
('Salmonellosis',2),
('SARS (Severe Acute Respiratory Syndrome)',2),
('Scabies',2),
('Schistosomiasis',2),
('Sepsis',2),
('Shigellosis (Bacillary dysentery)',2),
('Shingles (Herpes zoster)',2),
('Smallpox (Variola)',2),
('Sporotrichosis',2),
('Staphylococcal food poisoning',2),
('Staphylococcal infection',2),
('Strongyloidiasis',2),
('Subacute sclerosing panencephalitis',2),
('Syphilis',2),
('Taeniasis',2),
('Tetanus (Lockjaw)',2),
('Tinea barbae (Barbers itch)',2),
('Tinea capitis (Ringworm of the Scalp)',2),
('Tinea corporis (Ringworm of the Body)',2),
('Tinea cruris (Jock itch)',2),
('Tinea manum (Ringworm of the Hand)',2),
('Tinea nigra',2),
('Tinea pedis (Athletes foot)',2),
('Tinea unguium (Onychomycosis)',2),
('Tinea versicolor (Pityriasis versicolor)',2),
('Toxocariasis (Ocular Larva Migrans (OLM))',2),
('Toxocariasis (Visceral Larva Migrans (VLM))',2),
('Trinochccliasis',2),
('Trichinlosis',2),
('Trichomoniasis',2),
('Trichuriasis (Whipworm infection)',2),
('Tuberculosis',2),
('Tularemia',2),
('Ureaplasma urealyticum infection',2),
('Valley fever',2),
('Venezuelan equine encephalitis',2),
('Venezuelan hemorrhagic fever',2),
('Viral pneumonia',2),
('West Nile Fever',2),
('White piedra (Tinea blanca)',2),
('Yersinia pseudotuberculosis infection',2),
('Yersiniosis',2),
('Yellow fever',2),
('Zygomycosis',2)