using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Medical_System.Medical
{
    public class Diseases
    {
        Dictionary<string, string> Info = new Dictionary<string, string>();
        ObservableCollection<string> Name = new ObservableCollection<string>();
        public Diseases()
        {
            AutoFillMental();
            AutoFillPhyscial();
        }

        private void AutoFillMental()
        {
            Name.Add("Acute stress disorder");
            Name.Add("Adjustment disorders");
            Name.Add("Agoraphobia");
            Name.Add("Alcohol and substance abuse");
            Name.Add("Alcohol and substance dependence");
            Name.Add("Amnesia");
            Name.Add("Anxiety disorders");
            Name.Add("Anorexia nervosa");
            Name.Add("Antisocial personality disorder");
            Name.Add("Asperger's syndrome");
            Name.Add("Attention deficit hyperactivity disorder");
            Name.Add("Akiltism");
            Name.Add("Autism");
            Name.Add("Avoidant personality disorder");
            Name.Add("Bibliomania");
            Name.Add("Binge eating disorder");
            Name.Add("Bipolar disorder");
            Name.Add("Bipolar I disorder");
            Name.Add("Bipolar II disorder");
            Name.Add("Body dysmorphic disorder");
            Name.Add("Borderline personality disorder");
            Name.Add("Brief psychotic disorder");
            Name.Add("Bruxism");
            Name.Add("Bulimia nervosa");
            Name.Add("Conduct disorder");
            Name.Add("Conversion disorder");
            Name.Add("Cyclothymia");
            Name.Add("Delusional disorder");
            Name.Add("Dependent personality disorder");
            Name.Add("Depersonalization disorder");
            Name.Add("Depressive personality disorder");
            Name.Add("Dermotillomania");
            Name.Add("Disorder of written expression");
            Name.Add("Dissocial personality disorder");
            Name.Add("Dissociative fugue");
            Name.Add("Dissociative identity disorder");
            Name.Add("Down syndrome");
            Name.Add("Dyslexia");
            Name.Add("Dyspareunia");
            Name.Add("Dysthymia");
            Name.Add("Encopresis");
            Name.Add("Enuresis (bedwetting)");
            Name.Add("Erotomania");
            Name.Add("Exhibitionism");
            Name.Add("Expressive language disorder");
            Name.Add("Female and male orgasmic disorders");
            Name.Add("Female sexual arousal disorder");
            Name.Add("Folie à deux");
            Name.Add("Frotteurism");
            Name.Add("Gambling addiction");
            Name.Add("Gender identity disorder");
            Name.Add("Generalized anxiety disorder");
            Name.Add("General adaptation syndrome");
            Name.Add("Histrionic personality disorder");
            Name.Add("Primary hypersomnia");
            Name.Add("Hypoactive sexual desire disorder");
            Name.Add("Hypochondriasis");
            Name.Add("Hypomania");
            Name.Add("Hyperkinetic syndrome");
            Name.Add("Hypersexuality");
            Name.Add("Hysteria");
            Name.Add("Intermittent explosive disorder");
            Name.Add("Joubert syndrome");
            Name.Add("Kleptomania");
            Name.Add("Major depressive disorder");
            Name.Add("Male erectile disorder");
            Name.Add("Mania");
            Name.Add("Mental retardation");
            Name.Add("Munchausen syndrome");
            Name.Add("Mathematics disorder");
            Name.Add("Minor depressive disorder");
            Name.Add("Narcissistic personality disorder");
            Name.Add("Narcolepsy");
            Name.Add("Nightmare disorder");
            Name.Add("Obsessive-compulsive disorder");
            Name.Add("Obsessive-compulsive personality disorder");
            Name.Add("Onychophagia");
            Name.Add("Oppositional defiant disorder");
            Name.Add("Pain disorder");
            Name.Add("Panic attacks");
            Name.Add("Panic disorder");
            Name.Add("Paranoid personality disorder");
            Name.Add("Passive-aggressive personality disorder");
            Name.Add("Pathological gambling");
            Name.Add("Pervasive developmental disorder");
            Name.Add("Pica");
            Name.Add("Post-traumatic stress disorder");
            Name.Add("Premature ejaculation");
            Name.Add("Primary insomnia");
            Name.Add("Psychotic disorder");
            Name.Add("Pyromania");
            Name.Add("Reading disorder");
            Name.Add("Retts disorder");
            Name.Add("Rumination syndrome");
            Name.Add("Sadistic personality disorder");
            Name.Add("Schizoaffective disorder");
            Name.Add("Schizoid personality disorder");
            Name.Add("Schizophrenia");
            Name.Add("Schizophreniform disorder");
            Name.Add("Schizotypal personality disorder");
            Name.Add("Seasonal affective disorder");
            Name.Add("Self-defeating personality disorder");
            Name.Add("Separation anxiety disorder");
            Name.Add("Shared psychotic disorder");
            Name.Add("Sleep disorder");
            Name.Add("Sleep terror disorder");
            Name.Add("Sleepwalking disorder");
            Name.Add("Social phobia");
            Name.Add("Somatization disorder");
            Name.Add("Specific phobias");
            Name.Add("Stereotypic movement disorder");
            Name.Add("Stuttering");
            Name.Add("Tourette syndrome");
            Name.Add("Transient tic disorder");
            Name.Add("Trichotillomania");
        }

        public void AutoFillPhyscial()
        {
            Name.Add("Acinetobacter infections");
            Name.Add("Actinomycosis");
            Name.Add("African sleeping sickness (African trypanosomiasis)");
            Name.Add("AIDS (Acquired immunodeficiency syndrome)");
            Name.Add("Amebiasis");
            Name.Add("Anaplasmosis");
            Name.Add("Anthrax");
            Name.Add("Arcanobacterium haemolyticum infection");
            Name.Add("Argentine hemorrhagic fever");
            Name.Add("Ascariasis");
            Name.Add("Aspergillosis");
            Name.Add("Astrovirus infection");
            Name.Add("Babesiosis");
            Name.Add("Bacillus cereus infection");
            Name.Add("Bacterial pneumonia");
            Name.Add("Bacterial vaginosis");
            Name.Add("Bacteroides infection");
            Name.Add("Balantidiasis");
            Name.Add("Baylisascaris infection");
            Name.Add("BK virus infection");
            Name.Add("Black piedra");
            Name.Add("Blastocystis hominis infection");
            Name.Add("Blastomycosis");
            Name.Add("Bolivian hemorrhagic fever");
            Name.Add("Borrelia infection");
            Name.Add("Botulism (and Infant botulism)");
            Name.Add("Brazilian hemorrhagic fever");
            Name.Add("Brucellosis");
            Name.Add("Bubonic plague");
            Name.Add("Burkholderia infection");
            Name.Add("Buruli ulcer");
            Name.Add("Calicivirus infection (Norovirus and Sapovirus)");
            Name.Add("Campylobacteriosis");
            Name.Add("Candidiasis (Moniliasis; Thrush)");
            Name.Add("Cat-scratch disease");
            Name.Add("Cellulitis");
            Name.Add("Chagas Disease (American trypanosomiasis)");
            Name.Add("Chancroid");
            Name.Add("Chickenpox");
            Name.Add("Chlamydia");
            Name.Add("Chlamydophila pneumoniae infection (Taiwan acute respiratory agent or TWAR)");
            Name.Add("Cholera");
            Name.Add("Chromoblastomycosis");
            Name.Add("Clonorchiasis");
            Name.Add("Clostridium difficile infection");
            Name.Add("Coccidioidomycosis");
            Name.Add("Colorado tick fever (CTF)");
            Name.Add("Common cold (Acute viral rhinopharyngitis; Acute coryza)");
            Name.Add("Creutzfeldt-Jakob disease (CJD)");
            Name.Add("Crimean-Congo hemorrhagic fever (CCHF)");
            Name.Add("Cryptococcosis");
            Name.Add("Cryptosporidiosis");
            Name.Add("Cutaneous larva migrans (CLM)");
            Name.Add("Cyclosporiasis");
            Name.Add("Cysticercosis");
            Name.Add("Cytomegalovirus infection");
            Name.Add("Dengue fever");
            Name.Add("Dientamoebiasis");
            Name.Add("Diphtheria");
            Name.Add("Diphyllobothriasis");
            Name.Add("Dracunculiasis");
            Name.Add("Ebola hemorrhagic fever");
            Name.Add("Echinococcosis");
            Name.Add("Ehrlichiosis");
            Name.Add("Enterobiasis (Pinworm infection)");
            Name.Add("Enterococcus infection");
            Name.Add("Enterovirus infection");
            Name.Add("Epidemic typhus");
            Name.Add("Erythema infectiosum (Fifth disease)");
            Name.Add("Exanthem subitum (Sixth disease)");
            Name.Add("Fasciolopsiasis");
            Name.Add("Fasciolosis");
            Name.Add("Fatal familial insomnia (FFI)");
            Name.Add("Filariasis");
            Name.Add("Food poisoning by Clostridium perfringens");
            Name.Add("Free-living amebic infection");
            Name.Add("Fusobacterium infection");
            Name.Add("Gas gangrene (Clostridial myonecrosis)");
            Name.Add("Geotrichosis");
            Name.Add("Gerstmann-Sträussler-Scheinker syndrome (GSS)");
            Name.Add("Giardiasis");
            Name.Add("Glanders");
            Name.Add("Gnathostomiasis");
            Name.Add("Gonorrhea");
            Name.Add("Granuloma inguinale (Donovanosis)");
            Name.Add("Group A streptococcal infection");
            Name.Add("Group B streptococcal infection");
            Name.Add("Haemophilus influenzae infection");
            Name.Add("Hand, foot and mouth disease (HFMD)");
            Name.Add("Hantavirus Pulmonary Syndrome (HPS)");
            Name.Add("Helicobacter pylori infection");
            Name.Add("Hemolytic-uremic syndrome (HUS)");
            Name.Add("Hemorrhagic fever with renal syndrome (HFRS)");
            Name.Add("Hepatitis A");
            Name.Add("Hepatitis B");
            Name.Add("Hepatitis C");
            Name.Add("Hepatitis D");
            Name.Add("Hepatitis E");
            Name.Add("Herpes simplex");
            Name.Add("Histoplasmosis");
            Name.Add("Hookworm infection");
            Name.Add("Human bocavirus infection");
            Name.Add("Human ewingii ehrlichiosis");
            Name.Add("Human granulocytic anaplasmosis (HGA)");
            Name.Add("Human metapneumovirus infection");
            Name.Add("Human monocytic ehrlichiosis");
            Name.Add("Human papillomavirus (HPV) infection");
            Name.Add("Human parainfluenza virus infection");
            Name.Add("Hymenolepiasis");
            Name.Add("Epstein-Barr Virus Infectious Mononucleosis (Mono)");
            Name.Add("Influenza (flu)");
            Name.Add("Isosporiasis");
            Name.Add("Kawasaki disease");
            Name.Add("Keratitis");
            Name.Add("Kingella kingae infection");
            Name.Add("Kuru");
            Name.Add("Lassa fever");
            Name.Add("Legionellosis (Legionnaires' disease)");
            Name.Add("Legionellosis (Pontiac fever)");
            Name.Add("Leishmaniasis");
            Name.Add("Leprosy");
            Name.Add("Leptospirosis");
            Name.Add("Listeriosis");
            Name.Add("Lyme disease (Lyme borreliosis)");
            Name.Add("Lymphatic filariasis (Elephantiasis)");
            Name.Add("Lymphocytic choriomeningitis");
            Name.Add("Malaria");
            Name.Add("Marburg hemorrhagic fever (MHF)");
            Name.Add("Measles");
            Name.Add("Melioidosis (Whitmore's disease)");
            Name.Add("Meningitis");
            Name.Add("Meningococcal disease");
            Name.Add("Metagonimiasis");
            Name.Add("Microsporidiosis");
            Name.Add("Molluscum contagiosum (MC)");
            Name.Add("Monkeypox");
            Name.Add("Mumps");
            Name.Add("Murine typhus (Endemic typhus)");
            Name.Add("Mycoplasma pneumonia");
            Name.Add("Mycetoma");
            Name.Add("Myiasis");
            Name.Add("Neonatal conjunctivitis (Ophthalmia neonatorum)");
            Name.Add("(New) Variant Creutzfeldt-Jakob disease (vCJD, nvCJD)");
            Name.Add("Nocardiosis");
            Name.Add("Onchocerciasis (River blindness)");
            Name.Add("Paracoccidioidomycosis (South American blastomycosis)");
            Name.Add("Paragonimiasis");
            Name.Add("Pasteurellosis");
            Name.Add("Pediculosis capitis (Head lice)");
            Name.Add("Pediculosis corporis (Body lice)");
            Name.Add("Pediculosis pubis (Pubic lice, Crab lice)");
            Name.Add("Pelvic inflammatory disease (PID)");
            Name.Add("Pertussis (Whooping cough)");
            Name.Add("Plague");
            Name.Add("Pneumococcal infection");
            Name.Add("Pneumocystis pneumonia (PCP)");
            Name.Add("Pneumonia");
            Name.Add("Poliomyelitis");
            Name.Add("Prevotella infection");
            Name.Add("Primary amoebic meningoencephalitis (PAM)");
            Name.Add("Progressive multifocal leukoencephalopathy");
            Name.Add("Psittacosis");
            Name.Add("Q fever");
            Name.Add("Rabies");
            Name.Add("Rat-bite fever");
            Name.Add("Respiratory syncytial virus infection");
            Name.Add("Rhinosporidiosis");
            Name.Add("Rhinovirus infection");
            Name.Add("Rickettsial infection");
            Name.Add("Rickettsialpox");
            Name.Add("Rift Valley fever (RVF)");
            Name.Add("Rocky Mountain spotted fever (RMSF)");
            Name.Add("Rotavirus infection");
            Name.Add("Rubella");
            Name.Add("Salmonellosis");
            Name.Add("SARS (Severe Acute Respiratory Syndrome)");
            Name.Add("Scabies");
            Name.Add("Schistosomiasis");
            Name.Add("Sepsis");
            Name.Add("Shigellosis (Bacillary dysentery)");
            Name.Add("Shingles (Herpes zoster)");
            Name.Add("Smallpox (Variola)");
            Name.Add("Sporotrichosis");
            Name.Add("Staphylococcal food poisoning");
            Name.Add("Staphylococcal infection");
            Name.Add("Strongyloidiasis");
            Name.Add("Subacute sclerosing panencephalitis");
            Name.Add("Syphilis");
            Name.Add("Taeniasis");
            Name.Add("Tetanus (Lockjaw)");
            Name.Add("Tinea barbae (Barber's itch)");
            Name.Add("Tinea capitis (Ringworm of the Scalp)");
            Name.Add("Tinea corporis (Ringworm of the Body)");
            Name.Add("Tinea cruris (Jock itch)");
            Name.Add("Tinea manum (Ringworm of the Hand)");
            Name.Add("Tinea nigra");
            Name.Add("Tinea pedis (Athlete’s foot)");
            Name.Add("Tinea unguium (Onychomycosis)");
            Name.Add("Tinea versicolor (Pityriasis versicolor)");
            Name.Add("Toxocariasis (Ocular Larva Migrans (OLM))");
            Name.Add("Toxocariasis (Visceral Larva Migrans (VLM))");
            Name.Add("Trinochccliasis");
            Name.Add("Trichinlosis");
            Name.Add("Trichomoniasis");
            Name.Add("Trichuriasis (Whipworm infection)");
            Name.Add("Tuberculosis");
            Name.Add("Tularemia");
            Name.Add("Ureaplasma urealyticum infection");
            Name.Add("Valley fever");
            Name.Add("Venezuelan equine encephalitis");
            Name.Add("Venezuelan hemorrhagic fever");
            Name.Add("Viral pneumonia");
            Name.Add("West Nile Fever");
            Name.Add("White piedra (Tinea blanca)");
            Name.Add("Yersinia pseudotuberculosis infection");
            Name.Add("Yersiniosis");
            Name.Add("Yellow fever");
            Name.Add("Zygomycosis");
        }

        public ObservableCollection<string> getName()
        {
            return Name;
        }

        public void Populate(string toBeAdded)
        {
            Name.Add(toBeAdded);
        }



    }
}
